---
# User-specific Argo Workflow setup
# =================================
# Tim Friske <me@tifr.de>

# Default main variables
# ----------------------
user_dir: "{{ ansible_env.HOME }}"

bin_dir: "{{ user_dir }}/.local/bin"
