---
# User-specific OpenSSH setup
# ===========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Set up OpenSSH utility programs
  ansible.builtin.import_tasks: bin/main.yml

- name: Set up OpenSSH configuration files
  ansible.builtin.import_tasks: config/main.yml

- name: Set up OpenSSH keys
  ansible.builtin.import_tasks: key/main.yml
