---
# User-specific Tmux setup
# ========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ user_dir }}"

- name: Copy Tmux configuration file
  ansible.builtin.copy:
    src: config/tmux.conf
    dest: "{{ user_dir }}/.tmux.conf"
