---
# User-specific Util setup
# ========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy utility programs to binary directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - bin/*

- name: Create shortcuts to utility programs
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ bin_dir }}/{{ item.dest }}"
    state: link
  loop:
    - { src: df-common, dest: dfc }
    - { src: du-dirs, dest: dud }
    - { src: du-summary, dest: dus }
    - { src: file-backup, dest: fb }
    - { src: file-path, dest: fp }
    - { src: file-type, dest: ft }
    - { src: file-view, dest: fv }
    - { src: lower-case, dest: lc }
    - { src: upper-case, dest: uc }
