= Personal Software Configuration Management
Tim Friske <me@tifr.de>

Welcome to _Config_!

The project _Config_ is a personal project of mine.  It serves me to
manage the configuration files of my favorite software I use on a
regular basis.

When you are an IT enthusiast like me then you know how much time and
effort one is willing to spent in polishing his very own working
environment to perfection.  Therefore the _Git_ repository of this
project helps me to track the history of changes so that nothing is
lost.

I have chosen the generic name _Config_ for this project because even
though I primarily intend to configure my personal working environment
chances are that I will also set up the environments and services of the
client and server computers I control.  The common alternative name
_Dotfiles_ would be too limiting here because it gives the reader the
impression that this project and therefore its _Git_ repository only
encompasses configuration files living as hidden files or in hidden
folders underneath the user's home folder.

.RFC Request for Comments 2119
....
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
document are to be interpreted as described in RFC 2119.
....

For details please read the full <<rfc-2119, RFC 2119>> document.

== Copyright & Licensing

.GPLv3 GNU General Public License Version 3
....
Copyright (C) 2017  Tim Friske

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
....

For details please read the full <<gpl-3.0, GPLv3>> license.

[bibliography]
== Bibliography

[bibliography]
  * [[[rfc-2119]]] S. Bradner, _RFC Request for Comments 2119_, IETF
    Internet Engineering Task Force / Network Working Group,
    https://www.ietf.org/rfc/rfc2119.txt[online version]

  * [[[gpl-3.0]]] The _GPLv3_ authors, _GPLv3 GNU General Public License
    Version 3_, Free Software Foundation Incorporated,
    http://www.gnu.org/licenses/gpl-3.0.md[online version],
    link:Documentation/license/gpl-3.0.md[offline version]
