---
# System-specific setup
# =====================
# Tim Friske <me@tifr.de>

# Site tasks
# ----------
- name: Setup of hosts with configuration files
  hosts: "{{ hosts_var }}"
  roles:

    # Installation
    # ------------
    - role: installation
      tags:
        - software
        - packages

    # OpenSSH
    # -------
    - role: openssh
      tags:
        - openssh
        - openssh-client
        - openssh-server
        - ssh
        - sshd

    # Sysctl
    # ----
    - role: sysctl
      tags:
        - sysctl
        - kernel
        - parameter

    # User
    # ----
    - role: user
      tags:
        - user
