---
# User-specific GnuPG setup
# =========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  block:
    - name: Program directory
      file:
        path: "{{ bin_dir }}"
        state: directory
    - name: GnuPG configuration directory
      file:
        path: "{{ gnupg_dir }}"
        mode: u=rwx,g=,o=

- name: Copy GnuPG configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ gnupg_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - config/*

