---
# User-specific Alacritty setup
# =============================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Set up binary directory with programs and scripts
  ansible.builtin.import_tasks: bin/main.yml

- name: Set up config directory with configuration files
  ansible.builtin.import_tasks: config/main.yml
