---
# User-specific Alacritty setup
# =============================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Set up config directory with configuration files
  import_tasks: config/main.yml
