set encoding=utf-8
scriptencoding utf-8

" Vi Improved text editor configuration
" =====================================
" Tim Friske <me@tifr.de>
"
" Note: The option `encoding` and command `scriptencoding` must be
" set/executed at the top of this file in this order to have an effect.

" Enable overall sane _Vim_ defaults.
set nocompatible

" Load plug-ins and indendation rules according to detected file type.
filetype plugin indent on

" Enable syntax highlighting.
syntax on

" Full path to user's home directory.  Works on Linux, Mac and Windows.
let s:home_dir=fnamemodify('~', ':p')

" Behavior when displaying line numbers:
"
" relativenumber::
"   Efficiently operate in command mode by displaying the line numbers
"   relative to the current line where the cursor is at.  For example it
"   is not necessary anymore to manually count the lines before jumping
"   to a distant line.
" numberwidth::
"   Minimal number of columns to display the line numbers.  Do not waste
"   more columns than needed.
set relativenumber
if has('linebreak')
  set numberwidth=1
endif

" Show the line and column number of the cursor position.  When there is
" room, the relative position of the displayed text in the file is shown
" too, e.g. Top, Bot, All, 45%.
if has('cmdline_info')
  set ruler
endif

" Behavior when backspacing and deleting in _Insert_ mode:
"
" indent::
"   Allow over autoindent.
" eol::
"   Allow over line breaks to join lines.
" start::
"   Allow over start of insert.
set backspace=indent,eol,start

" Considerably increase the history of commands in command line mode.
set history=1000

" Abbreviate almost all messages.
set shortmess=filmnrwxoOtTI

" Recognize characters and numbers in octal, hexadecimal and binary
" format when adding to and subtracting from a number respectively.
set nrformats=alpha,octal,hex,bin

" Behavior when searching:
"
" incsearch::
"   Start/continue searching immediately with every key stroke.
" hlsearch::
"   Highlight all matches found.
" smartcase::
"   Search case-insensitive if only lower case characters were entered;
"   case-sensitive with mixed case characters.
" tagcase:
"   Follow the `smartcase` and `ignorecase` options (followscs) when
"   searching the tags.
" matchpairs::
"   Match also angle brackets when matching pairs.
if has('extra_search')
  set incsearch
  set hlsearch
endif
set smartcase
set tagcase=followscs
set matchpairs=(:),{:},[:],<:>

" Behavior when reindenting lines with tabulators and spaces, or
" shifting them left and right:
"
" expandtab::
"   Insert an appropriate number of spaces to insert a tabulator.
" smarttab::
"   Insert `shiftwidth` number of spaces in front of a line; `tabstop`
"   or `softtabstop` in other places.
" shiftround::
"   Round indent to multiples of `shiftwidth`.
set expandtab
set smarttab
set shiftround
