# Docker Image with Ansible
# =========================
# Tim Friske <me@tifr.de>

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN \
  set -o errexit xtrace
