# Docker Image with Ansible
# =========================
# Tim Friske <me@tifr.de>

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN \
  set -o errexit xtrace; \
  if command -v apt-get >/dev/null; then \
    apt-get update; \
    apt-get install --assume-yes python3 ansible; \
    apt-get clean; \
  fi
