# Ansible Role Test Docker Image
# ==============================
# Tim Friske <me@tifr.de>

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN \
  set -o errexit xtrace; \
  if command -v apt-get >/dev/null; then \
    apt-get update; \
    apt-get install --assume-yes python3; \
    apt-get clean; \
  elif command -v dnf >/dev/null; then \
    dnf makecache; \
    dnf --assumeyes install python3; \
    dnf clean all; \
  elif command -v zypper >/dev/null; then \
    zypper refresh; \
    zypper --non-interactive install python3; \
    zypper --non-interactive clean --all; \
  fi

CMD tail -f /dev/null
