---
# User-specific OpenSSH setup
# ===========================
# Tim Friske <me@tifr.de>

- name: Make target directories
  block:
    - name: OpenSSH configuration directory
      file:
        path: "{{ ssh_dir }}"
        mode: u=rwx,g=,o=

- name: Copy OpenSSH configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ ssh_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - config/*

- name: Set up OpenSSH configuration drop-in directory
  import_tasks: config.d/main.yml
