---
# User-specific Kubernetes setup
# ==============================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy programs and scripts to binary directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - bin/*

- name: Create shortcuts to Kubernetes programs
  ansible.builtin.file:
    src: "{{ link.src }}"
    dest: "{{ link.dest }}"
    force: yes
    state: link
  loop:
    - { src: kontext, dest: "{{ bin_dir }}/kkk" }
  loop_control:
    loop_var: link
    label: "{{ link.dest }} => {{ link.src }}"
