## Color Scheme Gruvbox Dark For Alacritty Terminal Emulator

colors:
  primary:
    #background: '#1d2021' # hard contrast
    background: '#282828' # default
    #background: '#32302f' # soft contrast
    foreground: '#ebdbb2' # default
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
