---
# User-specific OpenSSH setup
# ===========================
# Tim Friske <me@tifr.de>

# Drop-in configuration directory setup
# -------------------------------------
- name: Make target directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ config_dir }}"

- name: Copy OpenSSH drop-in configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ config_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - config/config.d/*
