---
# System-wide kernel parameter setup
# ==================================
# Tim Friske <me@tifr.de>

# OpenSUSE Tumbleweed variables
# -----------------------------

sysctl_kernel_parameters:
  -
    name: fs.inotify.max_user_watches
    value: 496902 # default: 248451
  -
    name: vm.max_map_count
    value: 131060 # default: 65530
