---
# User-specific Readline setup
# ============================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ user_dir }}"

- name: Copy Readline configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ user_dir }}/{{ item.dest | basename }}"
    mode: preserve
  loop:
    - { src: inputrc, dest: .inputrc }
    - { src: inputrc.fzf, dest: .inputrc.fzf }
