---
# User-specific Git setup
# =======================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy Git Branch Commands
  copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - command/branch/bin/git-b*

- name: Create shortcuts to Git Branch Commands
  file:
    src: "{{ item | basename }}"
    dest: "{{ bin_dir }}/\
           {{ item \
           | basename \
           | regex_replace('^git-b(.*)', '/gb\\1') }}"
    state: link
  with_fileglob:
    - command/branch/bin/git-b*

- block:
    - name: Create extra shortcuts to Git Branch Commands
      file:
        src: "{{ item.value }}"
        dest: "{{ bin_dir }}/{{ item.key }}"
        state: link
      loop: "{{ extra_shortcuts | dict2items }}"
    - name: Create extra shortcuts to Git Branch Commands
      file:
        src: "{{ item.key }}"
        dest: "{{ bin_dir }}/\
               {{ item.key \
               | regex_replace('^git-b(.*)', '/gb\\1') }}"
        state: link
      loop: "{{ extra_shortcuts | dict2items }}"
  vars:
    extra_shortcuts:
      git-bcc: git-bcf
      git-bdd: git-bdf
      git-bmm: git-bmf
