#!/usr/bin/env bash

# Numbered backup of single file
# ==============================
# Tim Friske <me@tifr.de>
#
# See also:
#   * man:bash[1]
#   * man:cp[1]

function bk {
  if [[ "$#" != 1 || ! -f "$1" ]]; then
    echo 'usage: bk <file>'
    exit 1
  fi
  cp --force --backup=numbered --verbose -- "$1" "$1"
}

bk "$@"
