#!/usr/bin/env bash

# Simple file type detection
# ==========================
# Tim Friske <me@tifr.de>
#
# Simple utility program to detect the type of a file.  Detects the
# types of any given number of files.  If a given file does not exist it
# is searched in the directories listed in the `PATH` environment
# variable and the first match is returned if any.
#
# See also:
#   * man:bash[1]
#   * man:file[1]

function file-type {
  if [[ "$#" == 0 ]]; then
    echo 'usage: file-type <file (on path)>...'
  fi
  local file
  for file in "$@"; do
    if [[ -e "$file" ]]; then
      file "$file"
    else
      file="$(type -P $file)"
      if [[ -n "$file" ]]; then
        file "$file"
      fi
    fi
  done
}

file-type "$@"
