#!/usr/bin/env bash
#
# Change directories with fuzzy finder
# ====================================
# Tim Friske <me@tifr.de>
#
# See also:
#   * man:bash[1]
#   * man:find[1]
#   * man:fzf[1]
#   * man:sort[1]
#   * fzf-cmd

set -o nounset -o pipefail -o errexit -o errtrace

function find_dirs {
  ${FZF_CD_FIND_DIRS_CMD:-find_dirs_default} 2> /dev/null
}

function find_dirs_default {
  find -L -mindepth 1 \
    \( \
      -path '*/\.*' \
      -o -fstype sysfs \
      -o -fstype devfs \
      -o -fstype devtmpfs \
      -o -fstype proc \
    \) \
    -prune \
    -o -type d \
    -print
}

function sort_dirs {
  ${FZF_CD_SORT_DIRS_CMD:-sort_dirs_default}
}

function sort_dirs_default {
  sort --sort=numeric
}

function select_dir {
  local options="${FZF_DEFAULT_OPTS:-} "
  FZF_DEFAULT_OPTS="$options" "$(fzf-cmd)"
}
