#!/usr/bin/env bash
#
# Fuzzy-find and pick records w/ Fzf
# ==================================
# Tim Friske <me@tifr.de>
#
# Dependencies::
#   _Bash_, _Cat_, _Fzf_

shopt -os nounset pipefail errexit errtrace

function print_help {
  1>&2 cat \
<<'HELP'
Help
====
Fuzzy-find and pick records with _Fzf_.

Usage
-----
.Command line syntax
----
fzf-pick [--help]
----

Options
-------
--help::
  Print this program's help text.

The program _Fzf-pick_ reads records from the standard input stream,
presents them in an interactive search screen to the user and waits for
her/him to fuzzy-find and pick the records s/he is interested in.  Once
the user made her/his selection _Fzf-pick_ writes the selected records
to the standard output stream.
HELP
}

function pick_records {
  fzf
}

function fzf_pick {
  if [[ "${1:-}" == '--help' ]]; then
    print_help
    exit
  fi

  pick_records
}

fzf_pick "$@"
