#!/usr/bin/env bash
#
# Find file system objects w/ Find for Fzf
# ========================================
# Tim Friske <me@tifr.de>
#
# Dependencies::
#   _Bash_

shopt -os nounset pipefail errexit errtrace

function print_help {
}

function fzf_find {
  if [[ "${1:-}" == '--help' ]]; then
    print_help
    exit
  fi
}

fzf_find "$@"
