#!/usr/bin/env bash
#
# Determine whether to use Tmux with Fzf
# ======================================
# Tim Friske <me@tifr.de>
#
# See also:
#   * man:bash[1]
#   * man:fzf[1]

shopt -os nounset pipefail errexit errtrace

function fzf_use_tmux {
  [[ "${FZF_TMUX:-0}" -ne 0
    && -n "${TMUX_PANE:-}"
    && "${LINES:-40}" -gt 15 ]]
}

fzf_use_tmux "$@"
