#!/usr/bin/env bash
#
# Fuzzy-find and pick records w/ Fzf
# ==================================
# Tim Friske <me@tifr.de>
#
# Dependencies::
#   _Bash_, _Cat_

shopt -os nounset pipefail errexit errtrace

function print_help {
  1>&2 cat \
<<'HELP'
Help
====
Fuzzy-find and pick records with _Fzf_.

Usage
-----
.Command line syntax
----
fzf-pick [--help]
----

Options
-------
--help::
  Print this program's help text.
HELP
}

function fzf_pick {
  if [[ "${1:-}" == '--help' ]]; then
    print_help
    exit
  fi
}

fzf_pick "$@"
