#!/usr/bin/env bash
#
# Quote records w/ Bash for Fzf
# =============================
# Tim Friske <me@tifr.de>
#
# Dependencies::
#   _Bash_, _Cat_

shopt -os nounset pipefail errexit errtrace

function print_help {
  1>&2 cat \
<<'HELP'
Help
====
Quote records with _Bash_ for _Fzf_.

Usage
-----
.Command line syntax
----
fzf-quote [--help]
----

Options
-------
--help::
  Print this program's help text.

The program _Fzf-quote_ reads unquoted records from the standard input
stream, quotes all special characters it finds in these records and
writes them in quoted form back to the standard output stream.

When _Fzf-quote's_ standard input stream is connected to a terminal it
expects each unquoted record to appear on a new line.  Otherwise, e.g.
when _Fzf-quote_ reads from a file or another program, it assumes each
unquoted record to be terminated with a `\0` null character.
HELP
}

function fzf_quote {
  if [[ "${1:-}" == '--help' ]]; then
    print_help
    exit
  fi

  local record=''
  if [[ -t 0 ]]; then
    while IFS='' read -r record; do
      printf '%q\n' "$record"
    done
  else
    while IFS='' read -r -d '' record; do
      printf '%q\n' "$record"
    done
  fi
}

fzf_quote "$@"
