#!/usr/bin/env bash
#
# Sort records w/ Sort for Fzf
# ============================
# Tim Friske <me@tifr.de>
#
# Dependencies::
#   _Bash_, _Cat_

shopt -os nounset pipefail errexit errtrace

function print_help {
  1>&2 cat \
<<'HELP'
Help
====
Sort records with _Sort_ for _Fzf_.

Usage
-----
.Command line syntax
----
fzf-sort [--help]
----

Options
-------
--help::
  Print this program's help text.
HELP
}

function fzf_sort {
  if [[ "${1:-}" == '--help' ]]; then
    print_help
    exit
  fi
}

fzf_sort "$@"
