#!/usr/bin/env bash
#
# Determine whether to use Tmux with Fzf
# ======================================
# Tim Friske <me@tifr.de>
#
# See also:
#   * man:bash[1]
#   * man:fzf[1]

set -o nounset -o pipefail -o errexit -o errtrace
