#!/usr/bin/env bash

# Fuzzy-find Git Branches
# =======================
# Tim Friske <me@tifr.de>
#
# Program to let the user list _Git_ branches, fuzzy-find, pick and
# perform actions on those s/he is interested in.

shopt -os nounset pipefail errexit errtrace
