#!/usr/bin/env bash
#
# Quote records w/ Bash for Fzf
# =============================
# Tim Friske <me@tifr.de>
#
# Dependencies::
#   _Bash_, _Cat_

shopt -os nounset pipefail errexit errtrace

function print_help {
  1>&2 cat \
<<'HELP'
Help
====
Quote records with _Bash_ for _Fzf_.

Usage
-----
.Command line syntax
----
fzf-quote [--help]
----

Options
-------
--help::
  Print this program's help text.
HELP
}

function fzf_quote {
  if [[ "${1:-}" == '--help' ]]; then
    print_help
    exit
  fi
}

fzf_quote "$@"
