#!/usr/bin/env bash

# Fuzzy-find Git Tags
# ===================
# Tim Friske <me@tifr.de>
#
# Program to let the user list _Git_ tags, fuzzy-find, pick and perform
# actions on those s/he is interested in.

shopt -os nounset pipefail errexit errtrace

function fzf_git_tag {
  local tag_options=()
  tag_options+=('--list')
  tag_options+=('--format=%(refname:short)')
  tag_options+=('--sort=version:refname')
  tag_options+=(${tag_opts:-})
}

fzf_git_tag "$@"
