#!/usr/bin/env bash

# Fuzzy-find Git Tags
# ===================
# Tim Friske <me@tifr.de>
#
# Program to let the user list _Git_ tags, fuzzy-find, pick and perform
# actions on those s/he is interested in.

shopt -os nounset pipefail errexit errtrace

function fzf_git_tag {
}

fzf_git_tag "$@"
