#!/usr/bin/env bash
#
# Fuzzy-find and pick records w/ Fzf
# ==================================
# Tim Friske <me@tifr.de>
#
# Dependencies::
#   _Bash_

shopt -os nounset pipefail errexit errtrace

function print_help {
}

function fzf_pick {
  if [[ "${1:-}" == '--help' ]]; then
    print_help
    exit
  fi
}

fzf_pick "$@"
