#!/usr/bin/env bash
#
# Retrieve command from history with fuzzy finder
# ===============================================
# Tim Friske <me@tifr.de>
#
# See also:
#   * man:bash[1]
#   * man:fzf[1]
#   * fzf-cmd

shopt -os nounset pipefail errexit errtrace
shopt -s extglob globstar

function fzf_history {
  if [[ -t 0 ]]; then
    echo 'usage: HISTTIMEFORMAT= history | fzf-history' 1>&2
    exit
  fi

  local options=''
  options+="--height ${FZF_TMUX_HEIGHT:-40%} "
  options+="${FZF_DEFAULT_OPTS:-} "
  options+="--tac -n2..,.. --tiebreak=index "
  options+="${FZF_HISTORY_FZF_OPTS:-} "
  local cmd="$(FZF_DEFAULT_OPTS="$options" "$(fzf-cmd)")"
  if [[ -n "$cmd" ]]; then
    printf '%s\n' "${cmd/#+([[:space:]])+([[:digit:]])+([[:space:]])/}"
  fi
}

fzf_history "$@"
