#!/usr/bin/env bash
#
# Find file system objects w/ Find for Fzf
# ========================================
# Tim Friske <me@tifr.de>
#
# Dependencies::
#   _Bash_

shopt -os nounset pipefail errexit errtrace
