#!/usr/bin/env bash
#
# Change directories with fuzzy finder
# ====================================
# Tim Friske <me@tifr.de>
#
# See also:
#   * man:bash[1]
#   * man:find[1]
#   * man:fzf[1]
#   * man:sort[1]
#   * fzf-cmd

set -o nounset -o pipefail -o errexit -o errtrace
