#!/usr/bin/env bash
#
# Retrieve command from history with fuzzy finder
# ===============================================
# Tim Friske <me@tifr.de>
#
# See also:
#   * man:bash[1]
#   * man:fzf[1]
#   * fzf-cmd

shopt -os nounset pipefail errexit errtrace
shopt -s extglob globstar

function fzf_history {
  if [[ -t 0 ]]; then
    echo 'usage: HISTTIMEFORMAT= history | fzf-history' 1>&2
    exit
  fi
}

fzf_history "$@"
