#!/usr/bin/env bash

# Fuzzy-find Git Branches
# =======================
# Tim Friske <me@tifr.de>
#
# Program to let the user list _Git_ branches, fuzzy-find, pick and
# perform actions on those s/he is interested in.

shopt -os nounset pipefail errexit errtrace

function fzf_git_branch {
  local branch_options=()
  branch_options+=('--list')
  branch_options+=('--format=%(refname:short)')
  branch_options+=('--sort=version:refname')
  branch_options+=(${branch_opts:-})
}

fzf_git_branch "$@"
