#!/usr/bin/env bash
#
# Run Fzf in appropriate environment
# ==================================
# Tim Friske <me@tifr.de>
#
# See also:
#   * man:bash[1]
#   * man:fzf[1]
#   * fzf-use-tmux

set -o nounset -o pipefail -o errexit -o errtrace
