#!/usr/bin/env bash
#
# Git Location
# ============
# Tim Friske <tifr@me.de>
#
# Display the location, i.e. the _Git_ branch, tag or commit at which
# the symbolic ref `HEAD` points.

shopt -os nounset pipefail errexit errtrace

function get_branch {
  git symbolic-ref --quiet --short "${ref:-HEAD}"
}

function get_tag {
  git describe --tags --exact-match "${ref:-HEAD}" 2> /dev/null
}

function get_commit {
  git rev-parse --short "${ref:-HEAD}"
}

function git_location {
}

git_location "$@"
