#!/usr/bin/env bash
#
# Git Location
# ============
# Tim Friske <tifr@me.de>
#
# Display the location, i.e. the _Git_ branch, tag or commit at which
# the symbolic ref `HEAD` points.

shopt -os nounset pipefail errexit errtrace
