#!/usr/bin/env bash

# Management of $PATH environment variable
# ========================================
# Tim Friske <me@tifr.de>
#
# See also:
#   * man:bash[1]

function path_raw {
  echo "$PATH"
}

function path_pretty {
  echo -e "${PATH//:/\\n}"
}

function path_appended {
  if path_contains "$1"; then
    echo "$PATH"
  else
    echo "$PATH:$1"
  fi
}

function path_prepended {
  if path_contains "$1"; then
    echo "$PATH"
  else
    echo "$1:$PATH"
  fi
}

function path_removed {
  if [[ -z "$1" ]]; then
    echo "$PATH"
    return
  fi
  local path_reduced="$PATH"
  if [[ "$path_reduced" =~ (^|(.*):)"$1"($|:(.*)) ]]; then
    local path_prefix="${BASH_REMATCH[2]}"
    local path_suffix="${BASH_REMATCH[4]}"
    if [[ -z "$path_prefix" ]]; then
      path_reduced="$path_suffix"
    elif [[ -z "$path_suffix" ]]; then
      path_reduced="$path_prefix"
    else
      path_reduced="$path_prefix:$path_suffix"
    fi
  fi
  echo "$path_reduced"
}

function path_contains {
  [[ -z "$1" || "$PATH" =~ (^|.*:)"$1"($|:.*) ]]
}

function path {
  case "$1" in
    raw) path_raw "${@:2}" ;;
    pretty) path_pretty "${@:2}" ;;
    appended) path_appended "${@:2}" ;;
    prepended) path_prepended "${@:2}" ;;
    removed) path_removed "${@:2}" ;;
  esac
}

path "$@"
