#!/usr/bin/env bash

# Management of $PATH environment variable
# ========================================
# Tim Friske <me@tifr.de>
#
# See also:
#   * man:bash[1]

function path_raw {
  echo "$PATH"
}

function path_pretty {
  echo -e "${PATH//:/\\n}"
}

function path_appended {
  if path_contains "$1"; then
    echo "$PATH"
  else
    echo "$PATH:$1"
  fi
}

function path_prepended {
  if path_contains "$1"; then
    echo "$PATH"
  else
    echo "$1:$PATH"
  fi
}

function path_removed {
}

function path_contains {
  [[ -z "$1" || "$PATH" =~ (^|.*:)"$1"($|:.*) ]]
}

function path {
  case "$1" in
    raw) path_raw "${@:2}" ;;
    pretty) path_pretty "${@:2}" ;;
    appended) path_appended "${@:2}" ;;
    prepended) path_prepended "${@:2}" ;;
    removed) path_removed "${@:2}" ;;
  esac
}

path "$@"
