#!/usr/bin/env bash

# Management of $PATH environment variable
# ========================================
# Tim Friske <me@tifr.de>
#
# See also:
#   * man:bash[1]

function path_raw {
  echo "$PATH"
}

function path {
  case "$1" in
    raw) path_raw "${@:2}" ;;
  esac
}

path "$@"
