#!/usr/bin/env bash

# TAR Tape Archive extraction
# ===========================
# Tim Friske <me@tifr.de>
#
# Simple tape archive (TAR) extraction utility program which optionally
# decompresses a given archive file before extracting its contents into
# a folder with the same name as the base name of the given archive
# file.  In case the folder already exists the archive contents are
# extracted into this folder and possibly overwrite entries of that
# folder.  Otherwise that folder is automatically created.

shopt -os nounset pipefail errexit errtrace

declare -r prog_name="${0##*/}"

function untar {
  if [[ "$#" != 1 || ! -f "$1" ]]; then
    echo "usage: $prog_name <file>"
    exit 1
  fi
  local archive_path="$1"
  local folder_path="${archive_path%.tar*}"
  echo '# Extracting files ...'
  echo '# ===================='
  tar \
    --extract \
    --file="$archive_path" \
    --verbose \
    -- \
    "$folder_path" \
    || true
  local message="... files extracted from $archive_path"
  local msg_sep="$(eval printf '=%.0s' {1..${#message}})"
  echo "# $msg_sep"
  echo "# $message"
}

untar "$@"
