---
# System-wide installation
# ========================
# Tim Friske <me@tifr.de>

# OpenSUSE Tumbleweed tasks
# -------------------------

- name: Add Microsoft Visual Studio Code zypper repository
  become: yes
  block:
  - ansible.builtin.rpm_key:
      key: https://packages.microsoft.com/keys/microsoft.asc
      fingerprint: BC528686B50D79E339D3721CEB3E94ADBE1229CF
      state: present
  - community.general.zypper_repository:
      name: microsoft-visual-studio-code
      description:
        Zypper repository to install Microsoft Visual Studio Code and
        update to new versions of it.
      repo: https://packages.microsoft.com/yumrepos/vscode
      state: present

- name: Add M17N Fonts zypper repository
  become: yes
  block:
  - ansible.builtin.rpm_key:
      key: https://download.opensuse.org/repositories/M17N:/fonts/openSUSE_Tumbleweed/repodata/repomd.xml.key
      fingerprint: 7DB53DFC040826C7678F7F27F4CCE1F4D15EE595
      state: present
  - community.general.zypper_repository:
      name: m17n-fonts
      description:
        Zypper repository to install many more fonts that are otherwise
        not available through the official repositories.
      repo: https://download.opensuse.org/repositories/M17N:/fonts/openSUSE_Tumbleweed
      state: present

- name: Install packages with zypper
  become: yes
  community.general.zypper:
    name: "{{ packages }}"
    state: present
