---
# System-wide installation
# ========================
# Tim Friske <me@tifr.de>

# Ubuntu tasks
# ------------

- name: Install packages with apt
  become: yes
  ansible.builtin.apt:
    name: "{{ packages.keys() }}"
    state: present
    install_recommends: yes
    update_cache: yes
    cache_valid_time: 86400
