---
# System-wide installation
# ========================
# Tim Friske <me@tifr.de>

# Ubuntu tasks
# ------------

- name: Add Microsoft Visual Studio Code apt repository
  become: yes
  block:
  - apt_key:
      id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  - apt_repository:
      repo: deb https://packages.microsoft.com/repos/code stable main
      state: present

- name: Install packages with apt
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install packages with snap
  become: yes
  snap:
    name: "{{ snaps }}"
    channel: stable
    classic: yes
    state: present
