---
# System-wide installation
# ========================
# Tim Friske <me@tifr.de>

# Ubuntu tasks
# ------------

- name: Add Alacritty Terminal Emulator apt repository
  become: yes
  block:
  - ansible.builtin.apt_key:
      id: 3A160895CC2CE253085D08A552B24DF7D43B5377
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3a160895cc2ce253085d08a552b24df7d43b5377
      state: present
  - apt_repository:
      repo: deb https://ppa.launchpadcontent.net/aslatter/ppa/ubuntu jammy main
      state: present

- name: Add Microsoft Visual Studio Code apt repository
  become: yes
  block:
  - ansible.builtin.apt_key:
      id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  - apt_repository:
      repo: deb https://packages.microsoft.com/repos/code stable main
      state: present

- name: Install packages with apt
  become: yes
  ansible.builtin.apt:
    name: "{{ packages.keys() }}"
    state: present
    install_recommends: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install packages with snap
  become: yes
  community.general.snap:
    name: "{{ snaps.keys() }}"
    channel: stable
    classic: yes
    state: present

- name: Connect plugs to slots in snaps
  become: yes
  loop: "{{ snap_connections }}"
  loop_control:
    loop_var: conn
    label: "{{ conn.snap }}:{{ conn.plug }} {{ conn.snap }}:{{ conn.slot }}"
  shell: snap connect {{ conn.snap }}:{{ conn.plug }} :{{ conn.slot }}

- name: Create shortcuts to utility programs
  become: yes
  ansible.builtin.file:
    src: "{{ link.src }}"
    dest: "{{ link.dest }}"
    force: yes
    state: link
  loop:
    - { src: "{{ bin_dir }}/fdfind", dest: "{{ local_bin_dir }}/fd" }
    - { src: "{{ bin_dir }}/sqlite3", dest: "{{ local_bin_dir }}/sqlite" }
  loop_control:
    loop_var: link
    label: "{{ link.dest }} => {{ link.src }}"

- name: Install Minikube
  ansible.builtin.import_tasks: ../minikube.yml
