---
# User-specific GnuPG setup
# =========================
# Tim Friske <me@tifr.de>

- name: Make target directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ systemd_user_dir }}"

- name: Copy GnuPG Systemd user unit files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ systemd_user_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - systemd/user/*
  loop_control:
    label: "{{ item | relpath }}"

- name: Enable GnuPG Systemd user unit files
  ansible.builtin.systemd:
    unit: "{{ item }}"
    scope: user
    enabled: yes
    state: started
    no_block: yes
  loop:
    - dirmngr.socket
    - gpg-agent.socket
    - gpg-agent-browser.socket
    - gpg-agent-extra.socket
    - gpg-agent-ssh.socket
