---
# User-specific Git setup
# =======================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy Git Push commands
  copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - command/push/bin/git-p*

- name: Create shortcuts to Git Push commands
  file:
    src: "{{ item | basename }}"
    dest: "{{ bin_dir }}/\
           {{ item \
           | basename \
           | regex_replace('^git-p(.*)', '/gp\\1') }}"
    state: link
  with_fileglob:
    - command/push/bin/git-p*
