---
# User-specific Fzf setup
# =======================
# Tim Friske <me@tifr.de>

- name: Make target directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy Fzf programs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - bin/*
  loop_control:
    label: "{{ item | relpath }}"

- name: Check if Fd program is in PATH
  ansible.builtin.shell: "which fd"
  register: fd_in_path
  ignore_errors: true
  changed_when: false

- name: Link Fzf Finder to Fzf Fd program
  ansible.builtin.file:
    src: "{{ bin_dir }}/fzf-fd"
    dest: "{{ bin_dir }}/fzf-finder"
    force: yes
    state: link
  when: fd_in_path.rc == 0

- name: Link Fzf Finder to Fzf Find program
  ansible.builtin.file:
    src: "{{ bin_dir }}/fzf-find"
    dest: "{{ bin_dir }}/fzf-finder"
    force: yes
    state: link
  when: fd_in_path.rc != 0
