# Client Credentials

This document describes how to store sensitive connection settings to connect to
MySQL database servers.

Instead of storing sensitive information such as plain-text passwords in
unencrypted form on disk MySQL's `mysql_config_editor` CLI program encrypts such
information before sotring it in the hidden `.mylogin.cnf` file in the user's
home directory.

The `mysql_config_editor` program groups information about the host, port, user
and password underneath sections which act as configuration profiles. These are
known as *login paths* in the context of MySQL. New login paths with the given
settings and the unspecified password, for which the user is prompted, can be
added by executing commands like the following:

[source,bash]
----
mysql_config_editor set \
  --login-path=PROFILE \
  --host=HOST_NAME_OR_IP_ADDRESS \
  --port=PORT_NUMBER \
  --user=USER_NAME \
  --password
# (User is prompted for password)
----

In order to list all of the already configured MySQL database server connections
the command `mysql_config_editor print --all` may be issued. To check the
connectivity to a new server or an existing one whose settings changed a command
such as `mysql --login-path=gcdb-test-admin --execute='select current_user()'`
can be executed.

Once set up the user can connect to different MySQL database servers or to the
same but as different database users simply by specifying the corresponding
login path via the `--login-path=PROFILE` option which is common to most of the
MySQL CLI programs. From here on the user is not prompted for passwords anymore.
