---
# User-specific Bash setup
# ========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ user_dir }}"

- name: Copy Bash startup files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ user_dir }}/{{ item.dest }}"
  loop:
    - { src: login, dest: .bash_login }
    - { src: rc, dest: .bashrc }
