---
# User-specific GnuPG setup
# =========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"
    - "{{ gnupg_dir }}"

- name: Set up GnuPG configuration files
  ansible.builtin.import_tasks: config/main.yml

- name: Set up GnuPG utility programs
  ansible.builtin.import_tasks: bin/main.yml

- name: Test if operating system is using Systemd
  ansible.builtin.find:
    patterns: systemctl
    paths: "{{ ansible_env.PATH.split(':') }}"
  register: systemctl

- name: Enable GnuPG daemons via Systemd user units
  ansible.builtin.import_tasks: systemd/user/main.yml
  when: systemctl.matched > 0
