---
# System-wide installation
# ========================
# Tim Friske <me@tifr.de>

# Argo Workflows tasks
# --------------------

- name: Create temporary directory for Argo Workflows
  block:
    - ansible.builtin.tempfile:
        prefix: argo-workflows-installation-
        state: directory
      register: argo_workflows_temp_dir
    - debug:
        var: argo_workflows_temp_dir.path

- name: Install Argo Workflow versions
  loop: "{{ argo_workflows_releases }}"
  loop_control:
    loop_var: release
    label: "Argo Workflows version {{ release.version }}"
  ansible.builtin.include_tasks: argo-workflow.yml

- name: Check if default Argo workflow version selected
  ansible.builtin.stat:
    path: /usr/local/bin/argo
  register: argo_default_file

- name: Select default Argo Workflows version 
  become: yes
  ansible.builtin.file:
    src: "/usr/local/bin/argo-{{ argo_workflows_releases[0].version }}"
    dest: /usr/local/bin/argo
    state: link
  when: argo_default_file.stat.exists == False
