---
# System-wide installation
# ========================
# Tim Friske <me@tifr.de>

# AWS CLI Version 2 tasks
# -----------------------

- name: Create temporary directory for AWS CLI version 2
  block:
    - ansible.builtin.tempfile:
        prefix: aws-cli-v2-installation-
        state: directory
      register: aws_cli_v2_temp_dir
    - debug:
        var: aws_cli_v2_temp_dir.path

- name: Download AWS CLI version 2 zip file
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: "{{ aws_cli_v2_temp_dir.path }}/aws-cli-v2.zip"
    checksum: sha256:37dc344830eba9d0376f52fce82fbcbcd32bd554e1ec6b5d2c36554e328eaf17

- name: Unpack AWS CLI version 2 zip file
  ansible.builtin.unarchive:
   src: "{{ aws_cli_v2_temp_dir.path }}/aws-cli-v2.zip"
   dest: "{{ aws_cli_v2_temp_dir.path }}"

- name: Install AWS CLI version 2
  become: yes
  ansible.builtin.shell: |
    {{ aws_cli_v2_temp_dir.path }}/aws/install --update
