---
# System-wide installation
# ========================
# Tim Friske <me@tifr.de>

# AWS EC2 Instance Selector tasks
# -------------------------------

- name: Download AWS EC2 Instance Selector program
  become: yes
  ansible.builtin.get_url:
    url: "{{ aws_ec2_instance_selector_url }}"
    dest: "{{ local_bin_dir }}/{{ aws_ec2_instance_selector_program }}-{{ aws_ec2_instance_selector_version }}"
    checksum: "{{ aws_ec2_instance_selector_checksum }}"
    mode: a+x

- name: Find AWS EC2 Instance Selector program paths
  ansible.builtin.find:
    path: "{{ local_bin_dir }}"
    pattern: "{{ aws_ec2_instance_selector_program }}-*"
  register: aws_ec2_instance_selector_program_paths

- name: Link AWS EC2 Instance Selector program (latest version)
  become: yes
  ansible.builtin.file:
    src: "{{ aws_ec2_instance_selector_program_paths.files | map(attribute='path') | community.general.version_sort | last | ansible.builtin.basename }}"
    dest: "{{ local_bin_dir }}/{{ aws_ec2_instance_selector_program }}"
    force: yes
    state: link
