---
# System-wide installation
# ========================
# Tim Friske <me@tifr.de>

# AWS CLI Version 2 tasks
# -----------------------

- name: Create temporary directory for Minikube
  block:
    - ansible.builtin.tempfile:
        prefix: minikube-installation-
        state: directory
      register: minikube_temp_dir
    - debug:
        var: minikube_temp_dir.path

- name: Download Minikube
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: "{{ minikube_temp_dir.path }}/minikube"
    checksum: sha256:9acd25706661b932ee98063147e58080cb949b92fd0d97b3b96dc5f898dcad21
    mode: a+x

- name: Install Minikube
  become: yes
  ansible.builtin.copy:
    src: "{{ minikube_temp_dir.path }}/minikube"
    dest: "/usr/local/bin/minikube"
    mode: a+x
