---
# User-specific Git setup
# =======================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy Git Checkout commands
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - command/checkout/bin/git-g*
  loop_control:
    label: "{{ item | relpath }}"

- name: Create shortcuts to Git Checkout commands
  ansible.builtin.file:
    src: "{{ item | basename }}"
    dest: "{{ bin_dir }}/\
      {{ item \
      | basename \
      | regex_replace('^git-g(.*)', '/gg\\1') }}"
    force: yes
    state: link
  with_fileglob:
    - command/checkout/bin/git-g*
  loop_control:
    label: "{{ item | relpath }}"
