## Font Scheme Hack For Alacritty Terminal Emulator

font:
  normal:
    family: Hack
    style: Regular
  bold:
    family: Hack
    style: Bold
  italic:
    family: Hack
    style: Italic
  bold_italic:
    family: Hack
    style: Bold Italic
  size: 6.0
  offset: {x: 0, y: 0}
  glyph_offset: {x: 0, y: 0}
