## Font Scheme Monospace For Alacritty Terminal Emulator

font:
  normal:
    family: monospace
    style: Regular
  bold:
    family: monospace
    style: Bold
  italic:
    family: monospace
    style: Italic
  bold_italic:
    family: monospace
    style: Bold Italic
  size: 9.0
  offset: {x: 0, y: 0}
  glyph_offset: {x: 0, y: 0}
  use_thin_strokes: true
