---
# Ansible Galaxy
# ==============

# Ansible Collections
# -------------------
# Ansible collections of roles the roles in this repository depend on.

collections:
  - ansible.posix
  - community.general

roles:
  - darkwizard242.googlechrome
