#!/usr/bin/env bash
#
# Main script of Config project
# =============================
# Tim Friske <me@tifr.de>

shopt -os nounset pipefail errexit errtrace

declare -r site_dir="$(dirname "$0")"

function site {
  cd -- "$site_dir"
}

site "$@"
