# Startup file for Bash interactive shells
# ========================================
# Tim Friske <me@tifr.de>
#
# The _Bash_ _Bourne Again Shell_ reads and executes commands from its
# configuration files but only if these exist and are readable.  When
# started as an interactive shell it first reads its system-wide startup
# file `/etc/bash.bashrc`.  It then continues to read its user-specific
# startup file `~/.bashrc`.
#
# This configuration file shall contain only non-default settings
# specific to interactive shells in order to keep it lean and thus easy
# to understand and maintain.  In case an interactive login shell is
# started this startup file shall be read and its commands executed by
# the first of _Bash's_ user-specific startup files for login shells
# that _Bash_ encounters, that is `~/.bash_profile`, `~/.bash_login` or
# `~/.profile`.
#
# See also:
#   * man:bash[1]
#   * link:{system-home}/bash.bashrc
#   * link:{user-home}/.bashrc
#   * link:{user-home}/.bash_profile
#   * link:{user-home}/.bash_login
#   * link:{user-home}/.profile

# Terminal settings
# -----------------

# Disable `CTRL-S` and `CTRL-Q` to stop and start terminal output
# because this function is not very useful and just confuses most users.
# The previously bound hot keys can be assigned new functions hereafter.
#
stty -ixon

# Shell options
# -------------

# Edit commands with Vi- instead of Emacs-like key bindings.
#
shopt -os vi

# Make it easy to name and navigate directories.
#
shopt -s autocd cdable_vars cdspell dirspell

# List any stopped and running jobs before exiting an interactive shell
# in order to not kill important jobs unintentionally but exit them
# manually, e.g. by saving their data first.  To list the remaining jobs
# is what most users would usually do if the shell they are about to
# exit reports that there are a number of stopped jobs.
#
shopt -s checkjobs

# Update window size after each command.
#
shopt -s checkwinsize

# Also store multi-line commands in history in case the user wants to
# adapt them later on, e.g. in case of syntax errors.
#
shopt -s cmdhist lithist

# Recognize extended set of patterns during pattern matching and path
# name expansion.
#
shopt -s extglob globstar

# Make command history more accessible.
#
shopt -s histappend histreedit histverify

# Don't overwrite files with `>` file redirection operator.  This
# setting may be overruled adhoc by using the `>|` operator.
#
shopt -os noclobber

# Attempt to complete commands once a non-empty prefix is given in order
# to not list the entire arsenal of commands but an already reduced list.
#
shopt -s no_empty_cmd_completion

# Ignore upper- and lower case during path name expansion and pattern
# matching.
#
shopt -s nocaseglob nocasematch

# Shell aliases
# -------------

source ~/.bash/rc.d/alias/sudo.bash
source ~/.bash/rc.d/alias/cd.bash
source ~/.bash/rc.d/alias/cp.bash
source ~/.bash/rc.d/alias/ln.bash
source ~/.bash/rc.d/alias/mv.bash
source ~/.bash/rc.d/alias/rm.bash
source ~/.bash/rc.d/alias/mkdir.bash
source ~/.bash/rc.d/alias/rmdir.bash
source ~/.bash/rc.d/alias/ls.bash
source ~/.bash/rc.d/alias/tar.bash
source ~/.bash/rc.d/alias/rsync.bash
source ~/.bash/rc.d/alias/sort.bash
source ~/.bash/rc.d/alias/wc.bash
source ~/.bash/rc.d/alias/df.bash
source ~/.bash/rc.d/alias/du.bash
source ~/.bash/rc.d/alias/file-xyz.bash
source ~/.bash/rc.d/alias/free.bash
source ~/.bash/rc.d/alias/info.bash
source ~/.bash/rc.d/alias/date.bash
source ~/.bash/rc.d/alias/xargs.bash
source ~/.bash/rc.d/alias/find.bash
source ~/.bash/rc.d/alias/diff.bash
source ~/.bash/rc.d/alias/grep.bash
source ~/.bash/rc.d/alias/os-distro.bash
source ~/.bash/rc.d/alias/pbcp-xclip-xsel.bash
source ~/.bash/rc.d/alias/ch-xyz.bash
source ~/.bash/rc.d/alias/xdg-open.bash
source ~/.bash/rc.d/alias/systemctl.bash
source ~/.bash/rc.d/alias/sed.bash
source ~/.bash/rc.d/alias/kubectl.bash
source ~/.bash/rc.d/alias/bind.bash
source ~/.bash/rc.d/alias/tmux.bash
source ~/.bash/rc.d/alias/jobs.bash
source ~/.bash/rc.d/alias/git.bash
source ~/.bash/rc.d/alias/fzf.bash

# Test if interactive shell has startup file with local overrides.
if [[ -f ~/.bashrc.local && -r ~/.bashrc.local ]]; then
  # Read and execute commands from that startup file.
  source ~/.bashrc.local
fi

# Test if _GnuPG_ for encrypting and signing data is installed.
if type -p gpg &> /dev/null; then
  # Let _GnuPG_ know on which terminal to interact with the user; for
  # example the _Gpg-agent_ daemon prompting for the passphrase.
  export GPG_TTY="$(tty)"
  echo UPDATESTARTUPTTY | gpg-connect-agent &> /dev/null
fi

# Test if neither a _Tmux_ nor _Screen_ nor _SSH_ session from
# `localhost` is running.
if ! [[ -n "$TMUX" || "$TERM" =~ screen
    || "$SSH_CONNECTION" =~ ^::1|^127\.0\.0\.1 ]]; then
  # Test if _Tmux_ is on the `$PATH`.
  if type -p tmux &> /dev/null; then
    # Try to attach to latest unattached session or start a new one.
    { tmux attach-session || tmux new-session; } &> /dev/null
  fi
fi
